repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|h)$
        exclude: ^third_party/

      - id: cppcheck
        name: cppcheck
        entry: cppcheck --error-exitcode=1 --enable=warning,style,performance,portability --inline-suppr --suppress=missingIncludeSystem
        language: system
        files: \.(c|h)$
        exclude: ^third_party/